# Generated by Django 5.0.7 on 2024-07-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_de_serie', models.CharField(max_length=100)),
                ('data_compra', models.CharField(max_length=10)),
                ('valor_compra', models.FloatField()),
            ],
        ),
    ]
