# Generated by Django 5.0.7 on 2024-07-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_compra',
            field=models.CharField(max_length=15),
        ),
    ]
