# Generated by Django 5.0.7 on 2024-07-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_equipamento_data_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_compra',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='valor_compra',
            field=models.FloatField(blank=True),
        ),
    ]
