# Generated by Django 5.0.7 on 2024-07-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_equipamento_data_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='valor_compra',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
