# Generated by Django 5.0.7 on 2024-07-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_equipamento_valor_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='valor_compra',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
